core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    # path('api/', include('api.urls'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('Yangiliklar', postNews, name='news'),
    path("E'lonlar", postAnnouns, name='announs'),
    
    path('Yangiliklar/<int:pk>', newsDetail, name='newsDetail'),
    path("E'lonlar/<int:pk>", elonDetail, name='elonDetail'),

    path("Filial", flial, name='flial'),
    path("Filial/Universitet-haqida", univerHaqida, name='univerHaqida'),
    path("Filial/Universitet-haqida/univerHaqidaDetail", univerHaqidaDetail, name='univerHaqidaDetail'),
    
    
    path("Filial/Fakultet", fakultet, name='fakultet'),
    path("Filial/Markazlar", markazlar, name='markazlar'),
    path("Filial/Markazlar/RTTM", markaz_detail, name='markaz_detail'),
    
    
    path("Filial/Bo'sh-ish-o'rinlari", jobs, name='jobs'),
    path("Filial/Rekvizitlar", rekvezit, name='rekvezit'),
    
    path("Filial/Raxbariyat", raxbariyat, name='raxbariyat'),
    path("Filial/history", history, name='history'),
    
    path("Filial/Struktura", struktura, name='struktura'),
    
    
    
    
    
]

templates/flial/Rekvizitlar.html
{% extends "__base.html" %}
{% load static %}
{% block main %}

    <section id="crambs" class="crambs">
        <div class="crambs-title">
            <svg width="390" height="69" viewBox="0 0 390 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.99986 0.468018H389.411L356.411 18.468H-26L6.99986 0.468018Z" fill="#537188" />
                <path d="M-85.0001 25.468H297.411L264.411 43.468H-118L-85.0001 25.468Z" fill="#537188" />
                <path d="M-172 50.468H210.411L177.411 68.468H-205L-172 50.468Z" fill="#537188" />
            </svg>
            <p class="crambs-title__text">Rekvizitlar</p>
            <svg width="386" height="69" viewBox="0 0 386 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M212 0.468018H594.411L561.411 18.468H179L212 0.468018Z" fill="#537188" />
                <path d="M120 25.468H502.411L469.411 43.468H87L120 25.468Z" fill="#537188" />
                <path d="M32.9999 50.468H415.411L382.411 68.468H0L32.9999 50.468Z" fill="#537188" />
            </svg>
        </div>
        <div class="crambs-body">
            <div class="crambs-body__item">
                <a class="crambs-body__item_link" href="{% url 'main:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="none">
                        <path
                            d="M7.54916 0.533177C8.38719 -0.173819 9.61281 -0.173819 10.4508 0.533177L17.2008 6.22772C17.7076 6.65523 18 7.28447 18 7.94747V17.7504C18 18.7169 17.2165 19.5004 16.25 19.5004H13.25C12.2835 19.5004 11.5 18.7169 11.5 17.7504V12.7504C11.5 12.3362 11.1642 12.0004 10.75 12.0004H7.25C6.83579 12.0004 6.5 12.3362 6.5 12.7504V17.7504C6.5 18.7169 5.7165 19.5004 4.75 19.5004H1.75C0.783502 19.5004 0 18.7169 0 17.7504V7.94747C0 7.28447 0.292405 6.65523 0.799155 6.22772L7.54916 0.533177Z"
                            />
                    </svg>
                </a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:flial' %}">Filial</a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:rekvezit' %}">Rekvizitlar</a>
            </div>
        </div>
    </section>

    <section id="requisites" class="requisites">
        <div class="container">

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            {% include "flial/__item1_left.html" %}

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            <div class="item2">
                <!-- <img class="bgIcon" src="../assets/images/pngwing.png" alt=""> -->
                <div class="item2-container">
                    
                    <div class="requisites-item" >
                        <div class="requisites-item__title">
                            Rivojlantirish jamg’armasi hisob raqami
                        </div>
                        <div class="requisites-item__text">
                            To‘lov rekvizitlari: O‘z.R. Moliya vazirligi Gʻaznachiligi 
                            <br>
                            x/r 23402000300100001010 MFO 00014 MB BB XKKM Toshkent shaxri 
                            <br>
                            INN: 201122919
                            <br>
                            Ta’lim muassasasi: O‘z MU Jizzax filiali 
                            <br>
                            sh/x 400110860084017094100079002 
                            <br>
                            INN: 306597922
                        </div>
                        <div class="requisites-item__btns">
                            <button class="requisites-item__btns_btn" onclick="alert('Nusxalandi')">
                                <img src="{% static 'images/copy-icon.svg' %}" alt="">
                            </button>
                            <button class="requisites-item__btns_btn" onclick="alert('Yuklandi')">
                                <img src="{% static 'images/download.svg' %}" alt="">
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <script>
        addEventListener("DOMContentLoaded", ()=>{
            // Nusxalash funksiyasi
            function copyText() {
                // 'requisites-item__text' sinfli elementni tanlaymiz
                const textElement = document.querySelector('.requisites-item__text');
                
                // Elementdagi barcha matnni olish
                const textToCopy = textElement.innerText;
                
                // Vaqtincha textarea yaratamiz
                const tempTextArea = document.createElement('textarea');
                tempTextArea.value = textToCopy;
                document.body.appendChild(tempTextArea);
                
                // Matnni tanlaymiz va nusxalaymiz
                tempTextArea.select();
                tempTextArea.setSelectionRange(0, 99999); // Mobil qurilmalar uchun
                
                try {
                    document.execCommand('copy');
                    alert('Nusxalandi');
                } catch (err) {
                    console.error('Nusxalashda xatolik:', err);
                }
                
                // Vaqtincha yaratilgan textarea ni o'chirib tashlaymiz
                document.body.removeChild(tempTextArea);
            }
        });
    </script>

{% endblock main %}

templates/flial/fakultet.html
{% extends "__base.html" %}
{% load static %}
{% block main %}

    <section id="crambs" class="crambs">
        <div class="crambs-title">
            <svg width="390" height="69" viewBox="0 0 390 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.99986 0.468018H389.411L356.411 18.468H-26L6.99986 0.468018Z" fill="#537188" />
                <path d="M-85.0001 25.468H297.411L264.411 43.468H-118L-85.0001 25.468Z" fill="#537188" />
                <path d="M-172 50.468H210.411L177.411 68.468H-205L-172 50.468Z" fill="#537188" />
            </svg>
            <p class="crambs-title__text">Fakultetlar</p>
            <svg width="386" height="69" viewBox="0 0 386 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M212 0.468018H594.411L561.411 18.468H179L212 0.468018Z" fill="#537188" />
                <path d="M120 25.468H502.411L469.411 43.468H87L120 25.468Z" fill="#537188" />
                <path d="M32.9999 50.468H415.411L382.411 68.468H0L32.9999 50.468Z" fill="#537188" />
            </svg>
        </div>
        <div class="crambs-body">
            <div class="crambs-body__item">
                <a class="crambs-body__item_link" href="{% url 'main:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="none">
                        <path
                            d="M7.54916 0.533177C8.38719 -0.173819 9.61281 -0.173819 10.4508 0.533177L17.2008 6.22772C17.7076 6.65523 18 7.28447 18 7.94747V17.7504C18 18.7169 17.2165 19.5004 16.25 19.5004H13.25C12.2835 19.5004 11.5 18.7169 11.5 17.7504V12.7504C11.5 12.3362 11.1642 12.0004 10.75 12.0004H7.25C6.83579 12.0004 6.5 12.3362 6.5 12.7504V17.7504C6.5 18.7169 5.7165 19.5004 4.75 19.5004H1.75C0.783502 19.5004 0 18.7169 0 17.7504V7.94747C0 7.28447 0.292405 6.65523 0.799155 6.22772L7.54916 0.533177Z"
                            />
                    </svg>
                </a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:flial' %}">Filial</a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:fakultet' %}">Fakultetlar</a>
            </div>
        </div>
    </section>
    <section id="faculties" class="faculties">
        <div class="container">
         

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            {% include "flial/__item1_left.html" %}

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}


            <div class="item2">
                <!-- <img class="bgIcon" src="../assets/images/pngwing.png" alt=""> -->
                <div class="item2-container">
                    <a href="#" class="faculties-item" onclick="alert('Salom')">
                        <div class="faculties-item__icon">
                            <img src="{% static 'images/faculties.png' %}" alt="">
                        </div>
                        <div class="faculties-item__text">Amaliy matematika</div>
                    </a>
                    <a href="#" class="faculties-item" onclick="alert('Salom')">
                        <div class="faculties-item__icon"> 
                            <img src="{% static 'images/faculties.png' %}" alt="">
                        </div>
                        <div class="faculties-item__text">Psixologiya</div>
                    </a>
                </div>
            </div>
        </div>
    </section>

{% endblock main %}

templates/flial/history.html
{% extends "__base.html" %}
{% load static %}
{% block main %}

    <section id="crambs" class="crambs">
        <div class="crambs-title">
            <svg width="390" height="69" viewBox="0 0 390 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.99986 0.468018H389.411L356.411 18.468H-26L6.99986 0.468018Z" fill="#537188" />
                <path d="M-85.0001 25.468H297.411L264.411 43.468H-118L-85.0001 25.468Z" fill="#537188" />
                <path d="M-172 50.468H210.411L177.411 68.468H-205L-172 50.468Z" fill="#537188" />
            </svg>
            <p class="crambs-title__text">Universitet tarixi</p>
            <svg width="386" height="69" viewBox="0 0 386 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M212 0.468018H594.411L561.411 18.468H179L212 0.468018Z" fill="#537188" />
                <path d="M120 25.468H502.411L469.411 43.468H87L120 25.468Z" fill="#537188" />
                <path d="M32.9999 50.468H415.411L382.411 68.468H0L32.9999 50.468Z" fill="#537188" />
            </svg>
        </div>
        <div class="crambs-body">
            <div class="crambs-body__item">
                <a class="crambs-body__item_link" href="{% url 'main:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="none">
                        <path
                            d="M7.54916 0.533177C8.38719 -0.173819 9.61281 -0.173819 10.4508 0.533177L17.2008 6.22772C17.7076 6.65523 18 7.28447 18 7.94747V17.7504C18 18.7169 17.2165 19.5004 16.25 19.5004H13.25C12.2835 19.5004 11.5 18.7169 11.5 17.7504V12.7504C11.5 12.3362 11.1642 12.0004 10.75 12.0004H7.25C6.83579 12.0004 6.5 12.3362 6.5 12.7504V17.7504C6.5 18.7169 5.7165 19.5004 4.75 19.5004H1.75C0.783502 19.5004 0 18.7169 0 17.7504V7.94747C0 7.28447 0.292405 6.65523 0.799155 6.22772L7.54916 0.533177Z"
                            />
                    </svg>
                </a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:flial' %}">Filial</a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:history' %}">Universitet tarixi</a>
            </div>
        </div>
    </section>
    <section id="historyuniver" class="historyuniver">
        <div class="container">
            
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            {% include "flial/__item1_left.html" %}

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            
            
            <div class="item2">
                <div class="title">
                    Mirzo Ulug'bek nomidagi O'zbekiston Milliy universiteti Jizzax filialida tahsil olayotgan talabalar
                    to'g'risida
                </div>
                <div class="body">
                    &nbsp;&nbsp;&nbsp;&nbsp;Mirzo Ulug'bek nomidagi O'zbekiston Milliy universiteti Jizzax filiali O'zbekiston Respublikasi
                    Prezidenti Shavkat Mirziyoevning 2019 yilning 30-31 yanvar kunlari Jizzax viloyatiga tashrifi
                    davomida bildirgan takliflari va O'zbekiston Respublikasi Vazirlar Mahkamasining 2019 yil 5 iyuldagi
                    563-sonli qarori hamda Jizzax viloyat hokimining 2019 yil 10 iyuldagi 261-sonli qaroriga asosan
                    tashkil etildi. <br>
                    &nbsp;&nbsp;&nbsp;&nbsp;2019/2020 o'quv yilidan boshlab filialda 1 ta fakul`tet, 2 ta kafedralarda 5 ta
                    bakalavr ta'lim yo'nalishi bo'yicha jami 14 nafar, shundan: Professor, fan doktorlari – 3 nafar,
                    Dotsent, fan nomzodlari – 1 nafar, assistentlar, o'qituvchilar – 10 nafar professor-o'qituvchilar
                    225 nafar talaba-yoshlarga  ta'lim berib kelmoqda. 
                </div>
            </div>
        </div>
    </section>

    {% endblock main %}

templates/flial/jobs.html
{% extends "__base.html" %}
{% load static %}
{% block main %}

    <section id="crambs" class="crambs">
        <div class="crambs-title">
            <svg width="390" height="69" viewBox="0 0 390 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.99986 0.468018H389.411L356.411 18.468H-26L6.99986 0.468018Z" fill="#537188" />
                <path d="M-85.0001 25.468H297.411L264.411 43.468H-118L-85.0001 25.468Z" fill="#537188" />
                <path d="M-172 50.468H210.411L177.411 68.468H-205L-172 50.468Z" fill="#537188" />
            </svg>
            <p class="crambs-title__text">Bo`sh ish o`rinlari</p>
            <svg width="386" height="69" viewBox="0 0 386 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M212 0.468018H594.411L561.411 18.468H179L212 0.468018Z" fill="#537188" />
                <path d="M120 25.468H502.411L469.411 43.468H87L120 25.468Z" fill="#537188" />
                <path d="M32.9999 50.468H415.411L382.411 68.468H0L32.9999 50.468Z" fill="#537188" />
            </svg>
        </div>
        <div class="crambs-body">
            <div class="crambs-body__item">
                <a class="crambs-body__item_link" href="{% url 'main:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="none">
                        <path
                            d="M7.54916 0.533177C8.38719 -0.173819 9.61281 -0.173819 10.4508 0.533177L17.2008 6.22772C17.7076 6.65523 18 7.28447 18 7.94747V17.7504C18 18.7169 17.2165 19.5004 16.25 19.5004H13.25C12.2835 19.5004 11.5 18.7169 11.5 17.7504V12.7504C11.5 12.3362 11.1642 12.0004 10.75 12.0004H7.25C6.83579 12.0004 6.5 12.3362 6.5 12.7504V17.7504C6.5 18.7169 5.7165 19.5004 4.75 19.5004H1.75C0.783502 19.5004 0 18.7169 0 17.7504V7.94747C0 7.28447 0.292405 6.65523 0.799155 6.22772L7.54916 0.533177Z"
                            />
                    </svg>
                </a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:flial' %}">Filial</a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:jobs' %}">Bo`sh ish o`rinlari</a>
            </div>
        </div>
    </section>
    <section id="jobs" class="jobs">
        <div class="container">
         
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            {% include "flial/__item1_left.html" %}

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}


            <div class="item2">
                <div class="jobs-item title">
                   <div class="jobs-item__text">Tаrkibiy bo'linmаlаrning nomlаnishi vа lаvozimlаr nomi</div>
                    <div class="jobs-item__text">Shtаt birlik-lаri soni</div>
                    <div class="jobs-item__text">Oylik mehnаtgа hаq to‘lаsh jаmg‘аrmаsi</div>
                </div>

                <div class="jobs-item box">
                    <div class="jobs-item__text">O'quv-uslubiy bo'lim</div>
                </div>
                <div class="jobs-item item">
                <div class="jobs-item__text item-text">Elektron kutubxonalar kutubxonachis</div>
                    <div class="jobs-item__text item-text">1</div>
                    <div class="jobs-item__text item-text">1 580 250</div>
                </div>

               
            </div>
        </div>
    </section>

{% endblock main %}

templates/flial/markazlar.html
{% extends "__base.html" %}
{% load static %}
{% block main %}

    <section id="crambs" class="crambs">
        <div class="crambs-title">
            <svg width="390" height="69" viewBox="0 0 390 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.99986 0.468018H389.411L356.411 18.468H-26L6.99986 0.468018Z" fill="#537188" />
                <path d="M-85.0001 25.468H297.411L264.411 43.468H-118L-85.0001 25.468Z" fill="#537188" />
                <path d="M-172 50.468H210.411L177.411 68.468H-205L-172 50.468Z" fill="#537188" />
            </svg>
            <p class="crambs-title__text">Markazlar</p>
            <svg width="386" height="69" viewBox="0 0 386 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M212 0.468018H594.411L561.411 18.468H179L212 0.468018Z" fill="#537188" />
                <path d="M120 25.468H502.411L469.411 43.468H87L120 25.468Z" fill="#537188" />
                <path d="M32.9999 50.468H415.411L382.411 68.468H0L32.9999 50.468Z" fill="#537188" />
            </svg>
        </div>
        <div class="crambs-body">
            <div class="crambs-body__item">
                <a class="crambs-body__item_link" href="{% url 'main:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="none">
                        <path
                            d="M7.54916 0.533177C8.38719 -0.173819 9.61281 -0.173819 10.4508 0.533177L17.2008 6.22772C17.7076 6.65523 18 7.28447 18 7.94747V17.7504C18 18.7169 17.2165 19.5004 16.25 19.5004H13.25C12.2835 19.5004 11.5 18.7169 11.5 17.7504V12.7504C11.5 12.3362 11.1642 12.0004 10.75 12.0004H7.25C6.83579 12.0004 6.5 12.3362 6.5 12.7504V17.7504C6.5 18.7169 5.7165 19.5004 4.75 19.5004H1.75C0.783502 19.5004 0 18.7169 0 17.7504V7.94747C0 7.28447 0.292405 6.65523 0.799155 6.22772L7.54916 0.533177Z"
                            />
                    </svg>
                </a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url "main:flial" %}">Filial</a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:markazlar' %}">Markazlar</a>
            </div>
        </div>
    </section>
    <section id="centers" class="centers">
        <div class="container">
            
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            {% include "flial/__item1_left.html" %}

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            <div class="item2">
                <!-- <img class="bgIcon" src="../assets/images/pngwing.png" alt=""> -->
                <div class="item2-container">
                    <a href="{% url 'main:markaz_detail' %}" class="centers-item">
                        <div class="centers-item__icon">
                            <img src="{% static 'images/rttmSvg.svg' %}" alt="">
                        </div>
                        <div class="centers-item__text">
                            RTTM-Raqamli ta’lim texnologiyalari markazi
                        </div>
                    </a>
                    <a href="#" class="centers-item">
                        <div class="centers-item__icon"> 
                            <img src="{% static 'images/armSvg.svg' %}" alt="">
                        </div>
                        <div class="centers-item__text">
                            ARM-Axborot resurs markazi
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

{% endblock main %}

templates/flial/universitet_haqida.html
{% extends "__base.html" %}
{% load static %}
{% block main %}

    <section id="crambs" class="crambs">
        <div class="crambs-title">
            <svg width="390" height="69" viewBox="0 0 390 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.99986 0.468018H389.411L356.411 18.468H-26L6.99986 0.468018Z" fill="#537188" />
                <path d="M-85.0001 25.468H297.411L264.411 43.468H-118L-85.0001 25.468Z" fill="#537188" />
                <path d="M-172 50.468H210.411L177.411 68.468H-205L-172 50.468Z" fill="#537188" />
            </svg>
            <p class="crambs-title__text">Universitet haqida</p>
            <svg width="386" height="69" viewBox="0 0 386 69" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M212 0.468018H594.411L561.411 18.468H179L212 0.468018Z" fill="#537188" />
                <path d="M120 25.468H502.411L469.411 43.468H87L120 25.468Z" fill="#537188" />
                <path d="M32.9999 50.468H415.411L382.411 68.468H0L32.9999 50.468Z" fill="#537188" />
            </svg>
        </div>
        <div class="crambs-body">
            <div class="crambs-body__item">
                <a class="crambs-body__item_link" href="{% url 'main:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="none">
                        <path
                            d="M7.54916 0.533177C8.38719 -0.173819 9.61281 -0.173819 10.4508 0.533177L17.2008 6.22772C17.7076 6.65523 18 7.28447 18 7.94747V17.7504C18 18.7169 17.2165 19.5004 16.25 19.5004H13.25C12.2835 19.5004 11.5 18.7169 11.5 17.7504V12.7504C11.5 12.3362 11.1642 12.0004 10.75 12.0004H7.25C6.83579 12.0004 6.5 12.3362 6.5 12.7504V17.7504C6.5 18.7169 5.7165 19.5004 4.75 19.5004H1.75C0.783502 19.5004 0 18.7169 0 17.7504V7.94747C0 7.28447 0.292405 6.65523 0.799155 6.22772L7.54916 0.533177Z"
                        />
                    </svg>
                </a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:flial' %}">Filial</a>
                <div class="crambs-body__item_dot"></div>
                <a class="crambs-body__item_link" href="{% url 'main:univerHaqida' %}">Universitet haqida</a>
            </div>
        </div>
    </section>
    <section id="aboutuniver" class="aboutuniver">
        <div class="container">
           


            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}

            {% include "flial/__item1_left.html" %}

            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            {% comment %}  {% endcomment %}
            



            <div class="item2">
                <div class="container">
                    
                    <a href="{% url 'main:univerHaqidaDetail' %}" class="aboutuniver-item">
                        <div class="header">
                            <img src="https://jbnuu.uz/storage/pages/January2022/img-1.jpg" alt="">
                            <div class="date">1918 - 1919</div>
                        </div>
                        <div class="body">
                            <div class="text">Turkiston Musulmon xalq universiteti</div>
                        </div>
                    </a>
                    
                </div>
            </div>
        </div>
    </section>


{% endblock main %}