core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    # path('api/', include('api.urls'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('Yangiliklar', postNews, name='news'),
    path("E'lonlar", postAnnouns, name='announs'),
    
    path('Yangiliklar/<int:pk>', newsDetail, name='newsDetail'),
    path("E'lonlar/<int:pk>", elonDetail, name='elonDetail'),

    path("Filial", flial, name='flial'),
    path("Filial/Universitet-haqida", univerHaqida, name='univerHaqida'),
    path("Filial/Universitet-haqida/univerHaqidaDetail", univerHaqidaDetail, name='univerHaqidaDetail'),
    
    
    path("Filial/Fakultet", fakultet, name='fakultet'),
    path("Filial/Markazlar", markazlar, name='markazlar'),
    path("Filial/Markazlar/RTTM", markaz_detail, name='markaz_detail'),
    
    
    path("Filial/Bo'sh-ish-o'rinlari", jobs, name='jobs'),
    path("Filial/Rekvizitlar", rekvezit, name='rekvezit'),
    
    path("Filial/Raxbariyat", raxbariyat, name='raxbariyat'),
    path("Filial/history", history, name='history'),
    
    path("Filial/Struktura", struktura, name='struktura'),
    
    
    
    
    
]

templates/__base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jbnuu</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'news/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'announs/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'newsview/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'announview/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'branch/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'aboutuniver/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'faculties/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'facultiesview/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'centerview/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'aboutuniverview/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'leading/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'history/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'structure/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'centers/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'jobs/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'requisites/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/swiper-bundle.min.css' %}">

    <!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
        $(function () {
            $("#header").load('/templates/header.html');
            $("#navbar").load('/templates/navbar.html');
            $("#footer").load('/templates/footer.html');
        });
    </script> -->
</head>
<body class="parallax">

    {% include "__navbar.html" %}
        
    {% block main %}{% endblock main %}
    {% block news %}{% endblock news %}
    {% block announ %}{% endblock announ %}
    {% block counterV %}{% endblock counterV %}
    {% block fast-links %}{% endblock fast-links %}
    {% block systems %}{% endblock systems %}
    {% block sites %}{% endblock sites %}
    
    {% include "__footer.html" %}


    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
    <script src="{% static 'main/js/swiper.js' %}"></script>
    <script src="{% static 'main/js/script.js' %}"></script>
</body>

</html>

templates/__footer.html
{% load static %}
<div id="footer" data-aos="fade-up" data-aos-duration="1200">
    <div class="img">
        <img class="img1" src="{% static 'images/Footer/img1.png' %}" alt="">
        <img class="img2" src="{% static 'images/Footer/img2.png' %}" alt="">
        <img class="img3" src="{% static 'images/Footer/img3.png' %}" alt="">   
    </div>
    <div class="footer">
        <div class="body">
            <div class="logoItem">
                <div>
                    <img class="itemLogo" src="{% static 'images/logo_white.png' %}" alt="">
                    <p class="itemText">
                        Mirzo Ulug‘bek nomidagi <br>
                        O`zbekiston Milliy universiteti <br>
                        Jizzax filiali
                    </p>
                </div>
            </div>
            <div class="group">
                <div class="fItem">
                    <div class="header">
                        <p>Bog`lanish uchun</p>
                        <div class="line"></div>
                    </div>
                    <div class="body">
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/email.svg' %}" alt="">
                            </div>
                            <div class="text">info@jbnuu.uz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/phone.svg' %}" alt="">
                            </div>
                            <div class="text">(998) 72-226-01-70</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/fax.svg' %}" alt="">
                            </div>
                            <div class="text">(998) 72-226-01-70</div>
                        </a>
                        <a href="" class="item" style="align-items: start;">
                            <div class="logo">
                                <img src="{% static 'images/Footer/clock.svg' %}" alt="">
                            </div>
                            <div class="text">Ish kuni: Dushanba-ShanbaIsh vaqti: 8:30-12:30 13:30-16:30</div>
                        </a>
                    </div>
                </div>
                
                <div class="fItem">
                    <div class="header">
                        <p>Ijtimoiy tarmoqlarda</p>
                        <div class="line"></div>
                    </div>
                    <div class="body">
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/telegram.svg' %}" alt="">
                            </div>
                            <div class="text">info@jbnuu.uz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/instagram.svg' %}" alt="">
                            </div>
                            <div class="text">Instagram  ijtimoy sahifamiz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/facebook.svg' %}" alt="">
                            </div>
                            <div class="text">Facebook  ijtimoy sahifamiz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/youtube.svg' %}" alt="">
                            </div>
                            <div class="text">Youtube kanalimiz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/tg_bot.svg' %}" alt="">
                            </div>
                            <div class="text">Murojaatingizni telegram <br> botimizga qoldiring</div>
                        </a>
                    </div>
                </div>
                
                <div class="fItem">
                    <div class="header">
                        <p>Manzil</p>
                        <div class="line"></div>
                    </div>
                    <div class="body">
                        <a href="" class="item" style="align-items: start;">
                            <div class="logo">
                                <img src="{% static 'images/Footer/location.svg' %}" alt="">
                            </div>
                            <div class="text">Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy 
                                              universitetining Jizzax filiali 130100, Jizzax 
                                              viloyati, Jizzax shahri Sh.Rashidov shox 
                                              ko'chasi, 259 uy</div>
                        </a>
                        <a href="" class="item" style="width: 100%; align-items: center; justify-content: center;">
                            <div class="android">
                                <img src="assets/images/Footer/android.svg" alt="">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyRight">
            Copyright © 2024 Mirzo Ulug‘bek nomidagi O‘zbekiston milliy universiteti 
            Jizzax filiali. Sayt test rejimida ishlamoqda.
        </div>
    </div>       

</div>

templates/__navbar.html
{% load static %}
<div id="header">
    <div>
        <div class="symbols">
            <a href="#">
                <img style="width: 2rem;" src="{% static 'images/flag.png' %}" alt="flag">
            </a>
            <a href="#">
                <img src="{% static 'images/gerb.png' %}" alt="gerb">
            </a>
            <a href="#">
                <img src="{% static 'images/nota.svg' %}" alt="nota">
            </a>
        </div>
        
        <div class="links">
            <a href="#">
                <img style="width: 1.2rem;" src="{% static 'images/Calendar.svg' %}" alt="">
                <h6>17.08.2024, shanba 17:00</h6>
            </a>
            <a href="#">
                <img src="{% static 'images/table.svg' %}" alt="">
                <h6>Talabalar dars jadvali</h6>
            </a>
            <a href="#">
                <img src="{% static 'images/e-book.svg' %}" alt="">
                <h6>Elektron kutubxona</h6>
            </a>
        </div>
        
        <div class="search">
            <i class="search__icon fa fa-search"></i>
            <input type="search" class="search__input" 
            placeholder="Qidiruv">
        </div>
        
        <div class="language">
            <div class="box">
                <img src="assets/images/language.svg" alt="">
                <div class="lang">
                    <h6>Uz</h6>
                    <p>|</p>
                    <h6>Ru</h6>
                    <p>|</p>
                    <h6>En</h6>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="navbar">
    <a href="{% url "main:index" %}" class="logoItem">
        <img class="logo" src="{% static 'images/logo.png' %}" alt="">
        <p class="logoText">
            MIRZO ULUG‘BEK NOMIDAGI <br>
            O‘ZBEKISTON MILLIY UNIVERSITETI <br>
            JIZZAX FILIALI <br>
        </p>
    </a>
    
    <div class="connect">
        <div class="item">
            <img src="{% static 'images/call_center 1.svg' %}" alt="">
            <div class="number">
                <p>72-226-01-71</p>
            </div>
        </div>
    
        <div class="item">
            <img src="{% static 'images/phone.svg' %}" alt="">
            <div class="number">
                <p>72-226-01-71</p>
                <p>72-226-01-71</p>
            </div>
        </div>
    </div>
    
    <div class="navBtns">
        <div class="navBtn btn1">
            <div class="text">
                <p>Yangiliklar</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
            <ul class="menu">
                <li><a href="{% url "main:news" %}" class="menuItem">Yangiliklar</a></li>
                <li><a href="{% url "main:announs" %}" class="menuItem">E'lonlar</a></li>
            </ul>          
        </div>
        <div class="navBtn btn2">
            <div class="text">
                <p>Filial</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
            <ul class="menu">
                <li><a href="{% url 'main:univerHaqida' %}" class="menuItem">Universitet haqida</a></li>
                <li><a href="{% url 'main:history' %}" class="menuItem">Filial tarixi</a></li>
                <li><a href="{% url 'main:struktura' %}" class="menuItem">Filial tuzilmasi</a></li>
                <li><a href="#" class="menuItem">Filial kengashi</a></li>
                <li><a href="{% url 'main:raxbariyat' %}" class="menuItem">Rahbariyat</a></li>
                <li><a href="{% url 'main:markazlar' %}" class="menuItem">Markazlar</a></li>
                <li><a href="#" class="menuItem">Bo'limlar</a></li>
                <li><a href="#" class="menuItem">Karyera markazi</a></li>
                <li><a href="#" class="menuItem">Sektorlar</a></li>
                <li><a href="{% url 'main:fakultet' %}" class="menuItem">Fakultetlar</a></li>
                <li><a href="#" class="menuItem">Kafedralar</a></li>
                <li><a href="{% url 'main:jobs' %}" class="menuItem">Bo‘sh ish o‘rinlari</a></li>
                <li><a href="#" class="menuItem">Bino inshoatlar joylashuvi</a></li>
                <li><a href="{% url 'main:rekvezit' %}" class="menuItem">Rekvizitlar</a></li>
                <li><a href="#" class="menuItem">Asosiy me'yoriy hujjatlar</a></li>
                <li><a href="#" class="menuItem">Manfaatlar to'qnashuvi to'g'risida</a></li>
            </ul>            
        </div>
        <div class="navBtn btn3">
            <div class="text">
                <p>Qabul-2024</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
            <ul class="menu">
                <li><a href="#" class="menuItem">Imtihon natijalari 2024-2025</a></li>
                <li><a href="#" class="menuItem">Filial tarixi</a></li>
                <li><a href="#" class="menuItem">Filial tuzilmasi</a></li>
                <li><a href="#" class="menuItem">Filial kengashi</a></li>
                <li><a href="#" class="menuItem">Rahbariyat</a></li>
                <li><a href="#" class="menuItem">Markazlar</a></li>
                <li><a href="#" class="menuItem">Bo'limlar</a></li>
                <li><a href="#" class="menuItem">Karyera markazi</a></li>
                <li><a href="#" class="menuItem">Sektorlar</a></li>
                <li><a href="#" class="menuItem">Fakultetlar</a></li>
                <li><a href="#" class="menuItem">Kafedralar</a></li>
                <li><a href="#" class="menuItem">Bo‘sh ish o‘rinlari</a></li>
                <li><a href="#" class="menuItem">Bino inshoatlar joylashuvi</a></li>
                <li><a href="#" class="menuItem">Rekvizitlar</a></li>
                <li><a href="#" class="menuItem">Asosiy me'yoriy hujjatlar</a></li>
                <li><a href="#" class="menuItem">Manfaatlar to'qnashuvi to'g'risida</a></li>
            </ul> 
        </div>
        <div class="navBtn btn4">
            <div class="text">
                <p>Doktorantura</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>  
        </div>
        <div class="navBtn btn5">
            <div class="text">
                <p>Interaktiv xizmatlar</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
        </div>
    </div>
</div>

templates/footer.html
{% load static %}
<div id="footer" data-aos="fade-up" data-aos-duration="1200">
    <div class="img">
        <img class="img1" src="{% static 'images/Footer/img1.png' %}" alt="">
        <img class="img2" src="{% static 'images/Footer/img2.png' %}" alt="">
        <img class="img3" src="{% static 'images/Footer/img3.png' %}" alt="">   
    </div>
    <div class="footer">
        <div class="body">
            <div class="logoItem">
                <div>
                    <img class="itemLogo" src="{% static 'images/logo_white.png' %}" alt="">
                    <p class="itemText">
                        Mirzo Ulug‘bek nomidagi <br>
                        O`zbekiston Milliy universiteti <br>
                        Jizzax filiali
                    </p>
                </div>
            </div>
            <div class="group">
                <div class="fItem">
                    <div class="header">
                        <p>Bog`lanish uchun</p>
                        <div class="line"></div>
                    </div>
                    <div class="body">
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/email.svg' %}" alt="">
                            </div>
                            <div class="text">info@jbnuu.uz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/phone.svg' %}" alt="">
                            </div>
                            <div class="text">(998) 72-226-01-70</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/fax.svg' %}" alt="">
                            </div>
                            <div class="text">(998) 72-226-01-70</div>
                        </a>
                        <a href="" class="item" style="align-items: start;">
                            <div class="logo">
                                <img src="{% static 'images/Footer/clock.svg' %}" alt="">
                            </div>
                            <div class="text">Ish kuni: Dushanba-Shanba Ish vaqti: 8:30-12:30 13:30-16:30</div>
                        </a>
                    </div>
                </div>
                
                <div class="fItem">
                    <div class="header">
                        <p>Ijtimoiy tarmoqlarda</p>
                        <div class="line"></div>
                    </div>
                    <div class="body">
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/telegram.svg' %}" alt="">
                            </div>
                            <div class="text">info@jbnuu.uz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/instagram.svg' %}" alt="">
                            </div>
                            <div class="text">Instagram  ijtimoy sahifamiz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/facebook.svg' %}" alt="">
                            </div>
                            <div class="text">Facebook  ijtimoy sahifamiz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/youtube.svg' %}" alt="">
                            </div>
                            <div class="text">Youtube kanalimiz</div>
                        </a>
                        <a href="" class="item">
                            <div class="logo">
                                <img src="{% static 'images/Footer/tg_bot.svg' %}" alt="">
                            </div>
                            <div class="text">Murojaatingizni telegram <br> botimizga qoldiring</div>
                        </a>
                    </div>
                </div>
                
                <div class="fItem">
                    <div class="header">
                        <p>Manzil</p>
                        <div class="line"></div>
                    </div>
                    <div class="body">
                        <a href="" class="item" style="align-items: start;">
                            <div class="logo">
                                <img src="{% static 'images/Footer/location.svg' %}" alt="">
                            </div>
                            <div class="text">Mirzo Ulug‘bek nomidagi O‘zbekiston Milliy 
                                              universitetining Jizzax filiali 130100, Jizzax 
                                              viloyati, Jizzax shahri Sh.Rashidov shox 
                                              ko'chasi, 259 uy</div>
                        </a>
                        <a href="" class="item" style="width: 100%; align-items: center; justify-content: center;">
                            <div class="android">
                                <img src="assets/images/Footer/android.svg" alt="">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyRight">
            Copyright © 2024 Mirzo Ulug‘bek nomidagi O‘zbekiston milliy universiteti 
            Jizzax filiali. Sayt test rejimida ishlamoqda.
        </div>
    </div>       

</div>

templates/header.html
{% load static %}
<div id="header">
    <div>
        <div class="symbols">
            <a href="#">
                <img style="width: 2rem;" src="{% static 'images/flag.png' %}" alt="flag">
            </a>
            <a href="#">
                <img src="{% static 'images/gerb.png' %}" alt="gerb">
            </a>
            <a href="#">
                <img src="{% static 'images/nota.svg' %}" alt="nota">
            </a>
        </div>
        
        <div class="links">
            <a href="#">
                <img style="width: 1.2rem;" src="{% static 'images/Calendar.svg' %}" alt="">
                <h6>17.08.2024, shanba 17:00</h6>
            </a>
            <a href="#">
                <img src="{% static 'images/table.svg' %}" alt="">
                <h6>Talabalar dars jadvali</h6>
            </a>
            <a href="#">
                <img src="{% static 'images/e-book.svg' %}" alt="">
                <h6>Elektron kutubxona</h6>
            </a>
        </div>
        
        <div class="search">
            <i class="search__icon fa fa-search"></i>
            <input type="search" class="search__input" 
            placeholder="Qidiruv">
        </div>
        
        <div class="language">
            <div class="box">
                <img src="assets/images/language.svg" alt="">
                <div class="lang">
                    <h6>Uz</h6>
                    <p>|</p>
                    <h6>Ru</h6>
                    <p>|</p>
                    <h6>En</h6>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="navbar">
    <a href="../index.html" class="logoItem">
        <img class="logo" src="{% static 'images/logo.png' %}" alt="">
        <p class="logoText">
            MIRZO ULUG‘BEK NOMIDAGI <br>
            O‘ZBEKISTON MILLIY UNIVERSITETI <br>
            JIZZAX FILIALI <br>
        </p>
    </a>
    
    <div class="connect">
        <div class="item">
            <img src="{% static 'images/call_center 1.svg' %}" alt="">
            <div class="number">
                <p>72-226-01-71</p>
            </div>
        </div>
    
        <div class="item">
            <img src="{% static 'images/phone.svg' %}" alt="">
            <div class="number">
                <p>72-226-01-71</p>
                <p>72-226-01-71</p>
            </div>
        </div>
    </div>
    
    <div class="navBtns">
        <div class="navBtn btn1">
            <div class="text">
                <p>Yangiliklar</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
            <ul class="menu">
                <li><a href="#" class="menuItem">Yangiliklar</a></li>
                <li><a href="#" class="menuItem">E'lonlar</a></li>
            </ul>          
        </div>
        <div class="navBtn btn2">
            <div class="text">
                <p>Filial</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
            <ul class="menu">
                <li><a href="#" class="menuItem">Universitet haqida</a></li>
                <li><a href="#" class="menuItem">Filial tarixi</a></li>
                <li><a href="#" class="menuItem">Filial tuzilmasi</a></li>
                <li><a href="#" class="menuItem">Filial kengashi</a></li>
                <li><a href="#" class="menuItem">Rahbariyat</a></li>
                <li><a href="#" class="menuItem">Markazlar</a></li>
                <li><a href="#" class="menuItem">Bo'limlar</a></li>
                <li><a href="#" class="menuItem">Karyera markazi</a></li>
                <li><a href="#" class="menuItem">Sektorlar</a></li>
                <li><a href="#" class="menuItem">Fakultetlar</a></li>
                <li><a href="#" class="menuItem">Kafedralar</a></li>
                <li><a href="#" class="menuItem">Bo‘sh ish o‘rinlari</a></li>
                <li><a href="#" class="menuItem">Bino inshoatlar joylashuvi</a></li>
                <li><a href="#" class="menuItem">Rekvizitlar</a></li>
                <li><a href="#" class="menuItem">Asosiy me'yoriy hujjatlar</a></li>
                <li><a href="#" class="menuItem">Manfaatlar to'qnashuvi to'g'risida</a></li>
            </ul>            
        </div>
        <div class="navBtn btn3">
            <div class="text">
                <p>Qabul-2024</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
            <ul class="menu">
                <li>
                    <a href="#" class="menuItem">Imtihon natijalari 2024-2025</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Filial tarixi</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Filial tuzilmasi</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Filial kengashi</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Rahbariyat</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Markazlar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Bo'limlar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Karyera markazi</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Sektorlar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Fakultetlar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Kafedralar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Bo‘sh ish o‘rinlari</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Bino inshoatlar joylashuvi</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Rekvizitlar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Asosiy me'yoriy hujjatlar</a>
                </li>
                <li>
                    <a href="#" class="menuItem">Manfaatlar to'qnashuvi to'g'risida</a>
                </li>
            </ul> 
        </div>
        <div class="navBtn btn4">
            <div class="text">
                <p>Doktorantura</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>  
        </div>
        <div class="navBtn btn5">
            <div class="text">
                <p>Interaktiv xizmatlar</p>
                <img src="{% static 'images/dropdowArrow.svg' %}" alt="">
            </div>
        </div>
    </div>
</div>